version: "3.9"

services:
  app:
    build: ../backend/api
    container_name: live-notes-api
    volumes:
      # Mount code for live reload during dev
      - ../backend/api:/var/www
    env_file:
      - ../backend/api/.env
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: live-notes-nginx
    ports:
      - "8000:80"
    volumes:
      - ../backend/api:/var/www
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  redis:
    image: redis:7-alpine
    container_name: live-notes-redis
    ports:
      - "6379:6379"

  notes-processor:
    build: ../services/notes-processor
    depends_on:
      - redis
